class piItem():
   
    # constructor
    def __init__(self, name, outputQuantity, inputName, inputQuantity):
        self.name = name
        self.outputQuantity = outputQuantity
        self.inputName = inputName
        self.inputQuantity = inputQuantity


piItems =[
    piItem('Bacteria',20,'Microorganisms',3000),
piItem('Biocells',5,'Precious Metals',40),
piItem('Biocells',5,'Biofuels',40),
piItem('Biofuels',20,'Carbon Compounds',3000),
piItem('Biomass',20,'Planktic Colonies',3000),
piItem('Biotech Research Reports',3,'Nanites',10),
piItem('Biotech Research Reports',3,'Construction Blocks',10),
piItem('Biotech Research Reports',3,'Livestock',10),
piItem('Broadcast Node',1,'Neocoms',6),
piItem('Broadcast Node',1,'Data Chips',6),
piItem('Broadcast Node',1,'High-Tech Transmitters',6),
piItem('Camera Drones',3,'Silicate Glass',10),
piItem('Camera Drones',3,'Rocket Fuel',10),
piItem('Chiral Structures',20,'Non-CS Crystals',3000),
piItem('Condensates',3,'Coolant',10),
piItem('Condensates',3,'Oxides',10),
piItem('Construction Blocks',5,'Reactive Metals',40),
piItem('Construction Blocks',5,'Toxic Metals',40),
piItem('Consumer Electronics',5,'Toxic Metals',40),
piItem('Consumer Electronics',5,'Chiral Structures',40),
piItem('Coolant',5,'Water',40),
piItem('Coolant',5,'Electrolytes',40),
piItem('Cryoprotectant Solution',3,'Test Cultures',10),
piItem('Cryoprotectant Solution',3,'Fertilizer',10),
piItem('Cryoprotectant Solution',3,'Synthetic Oil',10),
piItem('Data Chips',3,'Supertensile Plastics',10),
piItem('Data Chips',3,'Microfiber Shielding',10),
piItem('Electrolytes',20,'Ionic Solutions',3000),
piItem('Enriched Uranium',5,'Toxic Metals',40),
piItem('Enriched Uranium',5,'Precious Metals',40),
piItem('Fertilizer',5,'Bacteria',40),
piItem('Fertilizer',5,'Proteins',40),
piItem('Gel-Matrix Biopaste',3,'Oxides',10),
piItem('Gel-Matrix Biopaste',3,'Biocells',10),
piItem('Gel-Matrix Biopaste',3,'Superconductors',10),
piItem('Genetically Enhanced Livestock',5,'Proteins',40),
piItem('Genetically Enhanced Livestock',5,'Biomass',40),
piItem('Guidance Systems',3,'Water-Cooled CPU',10),
piItem('Guidance Systems',3,'Transmitter',10),
piItem('Hazmat Detection Systems',3,'Transmitter',10),
piItem('Hazmat Detection Systems',3,'Viral Agent',10),
piItem('Hazmat Detection Systems',3,'Polytextiles',10),
piItem('Hermetic Membranes',3,'Genetically Enhanced Livestock',10),
piItem('Hermetic Membranes',3,'Polyaramids',10),
piItem('High-Tech Transmitters',3,'Transmitter',10),
piItem('High-Tech Transmitters',3,'Polyaramids',10),
piItem('Industrial Explosives',3,'Fertilizer',10),
piItem('Industrial Explosives',3,'Polytextiles',10),
piItem('Industrial Fibers',20,'Autotrophs',3000),
piItem('Integrity Response Drones',1,'Planetary Vehicles',6),
piItem('Integrity Response Drones',1,'Hazmat Detection Systems',6),
piItem('Integrity Response Drones',1,'Gel-Matrix Biopaste',6),
piItem('Livestock',5,'Biofuels',40),
piItem('Livestock',5,'Proteins',40),
piItem('Mechanical Parts',5,'Precious Metals',40),
piItem('Mechanical Parts',5,'Reactive Metals',40),
piItem('Microfiber Shielding',5,'Industrial Fibers',40),
piItem('Microfiber Shielding',5,'Silicon',40),
piItem('Miniature Electronics',5,'Chiral Structures',40),
piItem('Miniature Electronics',5,'Silicon',40),
piItem('Nanites',5,'Bacteria',40),
piItem('Nanites',5,'Reactive Metals',40),
piItem('Nano-Factory',1,'Reactive Metals',40),
piItem('Nano-Factory',1,'Ukomi Superconductors',6),
piItem('Nano-Factory',1,'Industrial Explosives',6),
piItem('Neocoms',3,'Biocells',10),
piItem('Neocoms',3,'Silicate Glass',10),
piItem('Nuclear Reactors',3,'Microfiber Shielding',10),
piItem('Nuclear Reactors',3,'Enriched Uranium',10),
piItem('Organic Mortar Applicators',1,'Robotics',6),
piItem('Organic Mortar Applicators',1,'Bacteria',40),
piItem('Organic Mortar Applicators',1,'Condensates',6),
piItem('Oxides',5,'Oxygen',40),
piItem('Oxides',5,'Oxidizing Compound',40),
piItem('Oxidizing Compound',20,'Reactive Gas',3000),
piItem('Oxygen',20,'Noble Gas',3000),
piItem('Planetary Vehicles',3,'Miniature Electronics',10),
piItem('Planetary Vehicles',3,'Mechanical Parts',10),
piItem('Planetary Vehicles',3,'Supertensile Plastics',10),
piItem('Plasmoids',20,'Suspended Plasma',3000),
piItem('Polyaramids',5,'Industrial Fibers',40),
piItem('Polyaramids',5,'Oxidizing Compound',40),
piItem('Polytextiles',5,'Industrial Fibers',40),
piItem('Polytextiles',5,'Biofuels',40),
piItem('Precious Metals',20,'Noble Metals',3000),
piItem('Proteins',20,'Complex Organisms',3000),
piItem('Reactive Metals',20,'Base Metals',3000),
piItem('Recursive Computing Module',1,'Transcranial Microcontrollers',6),
piItem('Recursive Computing Module',1,'Guidance Systems',6),
piItem('Recursive Computing Module',1,'Synthetic Synapses',6),
piItem('Robotics',3,'Consumer Electronics',10),
piItem('Robotics',3,'Mechanical Parts',10),
piItem('Rocket Fuel',5,'Plasmoids',40),
piItem('Rocket Fuel',5,'Electrolytes',40),
piItem('Self-Harmonizing Power Core',1,'Camera Drones',6),
piItem('Self-Harmonizing Power Core',1,'Hermetic Membranes',6),
piItem('Self-Harmonizing Power Core',1,'Nuclear Reactors',6),
piItem('Silicate Glass',5,'Silicon',40),
piItem('Silicate Glass',5,'Oxidizing Compound',40),
piItem('Silicon',20,'Felsic Magma',3000),
piItem('Smartfab Units',3,'Miniature Electronics',10),
piItem('Smartfab Units',3,'Construction Blocks',10),
piItem('Sterile Conduits',1,'Smartfab Units',6),
piItem('Sterile Conduits',1,'Vaccines',6),
piItem('Sterile Conduits',1,'Water',40),
piItem('Supercomputers',3,'Water-Cooled CPU',10),
piItem('Supercomputers',3,'Consumer Electronics',10),
piItem('Supercomputers',3,'Coolant',10),
piItem('Superconductors',5,'Water',40),
piItem('Superconductors',5,'Plasmoids',40),
piItem('Supertensile Plastics',5,'Biomass',40),
piItem('Supertensile Plastics',5,'Oxygen',40),
piItem('Synthetic Oil',5,'Electrolytes',40),
piItem('Synthetic Oil',5,'Oxygen',40),
piItem('Synthetic Synapses',3,'Supertensile Plastics',10),
piItem('Synthetic Synapses',3,'Test Cultures',10),
piItem('Test Cultures',5,'Bacteria',40),
piItem('Test Cultures',5,'Water',40),
piItem('Toxic Metals',20,'Heavy Metals',3000),
piItem('Transcranial Microcontrollers',3,'Nanites',10),
piItem('Transcranial Microcontrollers',3,'Biocells',10),
piItem('Transmitter',5,'Chiral Structures',40),
piItem('Transmitter',5,'Plasmoids',40),
piItem('Ukomi Superconductors',3,'Synthetic Oil',10),
piItem('Ukomi Superconductors',3,'Superconductors',10),
piItem('Vaccines',3,'Viral Agent',10),
piItem('Vaccines',3,'Livestock',10),
piItem('Viral Agent',5,'Biomass',40),
piItem('Viral Agent',5,'Bacteria',40),
piItem('Water',20,'Aqueous Liquids',3000),
piItem('Water-Cooled CPU',5,'Water',40),
piItem('Water-Cooled CPU',5,'Reactive Metals',40),
piItem('Wetware Mainframe',1,'Biotech Research Reports',6),
piItem('Wetware Mainframe',1,'Cryoprotectant Solution',6),
piItem('Wetware Mainframe',1,'Supercomputers',6),

]








items = [{"typeName":"Bacteria","productQuantity":"20","productVolume":"3,8","eduktName":"Microorganisms","eduktQuantity":"3000"},
{"typeName":"Biocells","productQuantity":"5","productVolume":"3,75","eduktName":"Precious Metals","eduktQuantity":"40"},
{"typeName":"Biocells","productQuantity":"5","productVolume":"3,75","eduktName":"Biofuels","eduktQuantity":"40"},
{"typeName":"Biofuels","productQuantity":"20","productVolume":"3,8","eduktName":"Carbon Compounds","eduktQuantity":"3000"},
{"typeName":"Biomass","productQuantity":"20","productVolume":"3,8","eduktName":"Planktic Colonies","eduktQuantity":"3000"},
{"typeName":"Biotech Research Reports","productQuantity":"3","productVolume":"9","eduktName":"Nanites","eduktQuantity":"10"},
{"typeName":"Biotech Research Reports","productQuantity":"3","productVolume":"9","eduktName":"Construction Blocks","eduktQuantity":"10"},
{"typeName":"Biotech Research Reports","productQuantity":"3","productVolume":"9","eduktName":"Livestock","eduktQuantity":"10"},
{"typeName":"Broadcast Node","productQuantity":"1","productVolume":"50","eduktName":"Neocoms","eduktQuantity":"6"},
{"typeName":"Broadcast Node","productQuantity":"1","productVolume":"50","eduktName":"Data Chips","eduktQuantity":"6"},
{"typeName":"Broadcast Node","productQuantity":"1","productVolume":"50","eduktName":"High-Tech Transmitters","eduktQuantity":"6"},
{"typeName":"Camera Drones","productQuantity":"3","productVolume":"9","eduktName":"Silicate Glass","eduktQuantity":"10"},
{"typeName":"Camera Drones","productQuantity":"3","productVolume":"9","eduktName":"Rocket Fuel","eduktQuantity":"10"},
{"typeName":"Chiral Structures","productQuantity":"20","productVolume":"3,8","eduktName":"Non-CS Crystals","eduktQuantity":"3000"},
{"typeName":"Condensates","productQuantity":"3","productVolume":"9","eduktName":"Coolant","eduktQuantity":"10"},
{"typeName":"Condensates","productQuantity":"3","productVolume":"9","eduktName":"Oxides","eduktQuantity":"10"},
{"typeName":"Construction Blocks","productQuantity":"5","productVolume":"3,75","eduktName":"Reactive Metals","eduktQuantity":"40"},
{"typeName":"Construction Blocks","productQuantity":"5","productVolume":"3,75","eduktName":"Toxic Metals","eduktQuantity":"40"},
{"typeName":"Consumer Electronics","productQuantity":"5","productVolume":"3,75","eduktName":"Toxic Metals","eduktQuantity":"40"},
{"typeName":"Consumer Electronics","productQuantity":"5","productVolume":"3,75","eduktName":"Chiral Structures","eduktQuantity":"40"},
{"typeName":"Coolant","productQuantity":"5","productVolume":"3,75","eduktName":"Water","eduktQuantity":"40"},
{"typeName":"Coolant","productQuantity":"5","productVolume":"3,75","eduktName":"Electrolytes","eduktQuantity":"40"},
{"typeName":"Cryoprotectant Solution","productQuantity":"3","productVolume":"9","eduktName":"Test Cultures","eduktQuantity":"10"},
{"typeName":"Cryoprotectant Solution","productQuantity":"3","productVolume":"9","eduktName":"Fertilizer","eduktQuantity":"10"},
{"typeName":"Cryoprotectant Solution","productQuantity":"3","productVolume":"9","eduktName":"Synthetic Oil","eduktQuantity":"10"},
{"typeName":"Data Chips","productQuantity":"3","productVolume":"9","eduktName":"Supertensile Plastics","eduktQuantity":"10"},
{"typeName":"Data Chips","productQuantity":"3","productVolume":"9","eduktName":"Microfiber Shielding","eduktQuantity":"10"},
{"typeName":"Electrolytes","productQuantity":"20","productVolume":"3,8","eduktName":"Ionic Solutions","eduktQuantity":"3000"},
{"typeName":"Enriched Uranium","productQuantity":"5","productVolume":"3,75","eduktName":"Toxic Metals","eduktQuantity":"40"},
{"typeName":"Enriched Uranium","productQuantity":"5","productVolume":"3,75","eduktName":"Precious Metals","eduktQuantity":"40"},
{"typeName":"Fertilizer","productQuantity":"5","productVolume":"3,75","eduktName":"Bacteria","eduktQuantity":"40"},
{"typeName":"Fertilizer","productQuantity":"5","productVolume":"3,75","eduktName":"Proteins","eduktQuantity":"40"},
{"typeName":"Gel-Matrix Biopaste","productQuantity":"3","productVolume":"9","eduktName":"Oxides","eduktQuantity":"10"},
{"typeName":"Gel-Matrix Biopaste","productQuantity":"3","productVolume":"9","eduktName":"Biocells","eduktQuantity":"10"},
{"typeName":"Gel-Matrix Biopaste","productQuantity":"3","productVolume":"9","eduktName":"Superconductors","eduktQuantity":"10"},
{"typeName":"Genetically Enhanced Livestock","productQuantity":"5","productVolume":"3,75","eduktName":"Proteins","eduktQuantity":"40"},
{"typeName":"Genetically Enhanced Livestock","productQuantity":"5","productVolume":"3,75","eduktName":"Biomass","eduktQuantity":"40"},
{"typeName":"Guidance Systems","productQuantity":"3","productVolume":"9","eduktName":"Water-Cooled CPU","eduktQuantity":"10"},
{"typeName":"Guidance Systems","productQuantity":"3","productVolume":"9","eduktName":"Transmitter","eduktQuantity":"10"},
{"typeName":"Hazmat Detection Systems","productQuantity":"3","productVolume":"9","eduktName":"Transmitter","eduktQuantity":"10"},
{"typeName":"Hazmat Detection Systems","productQuantity":"3","productVolume":"9","eduktName":"Viral Agent","eduktQuantity":"10"},
{"typeName":"Hazmat Detection Systems","productQuantity":"3","productVolume":"9","eduktName":"Polytextiles","eduktQuantity":"10"},
{"typeName":"Hermetic Membranes","productQuantity":"3","productVolume":"9","eduktName":"Genetically Enhanced Livestock","eduktQuantity":"10"},
{"typeName":"Hermetic Membranes","productQuantity":"3","productVolume":"9","eduktName":"Polyaramids","eduktQuantity":"10"},
{"typeName":"High-Tech Transmitters","productQuantity":"3","productVolume":"9","eduktName":"Transmitter","eduktQuantity":"10"},
{"typeName":"High-Tech Transmitters","productQuantity":"3","productVolume":"9","eduktName":"Polyaramids","eduktQuantity":"10"},
{"typeName":"Industrial Explosives","productQuantity":"3","productVolume":"9","eduktName":"Fertilizer","eduktQuantity":"10"},
{"typeName":"Industrial Explosives","productQuantity":"3","productVolume":"9","eduktName":"Polytextiles","eduktQuantity":"10"},
{"typeName":"Industrial Fibers","productQuantity":"20","productVolume":"3,8","eduktName":"Autotrophs","eduktQuantity":"3000"},
{"typeName":"Integrity Response Drones","productQuantity":"1","productVolume":"50","eduktName":"Planetary Vehicles","eduktQuantity":"6"},
{"typeName":"Integrity Response Drones","productQuantity":"1","productVolume":"50","eduktName":"Hazmat Detection Systems","eduktQuantity":"6"},
{"typeName":"Integrity Response Drones","productQuantity":"1","productVolume":"50","eduktName":"Gel-Matrix Biopaste","eduktQuantity":"6"},
{"typeName":"Livestock","productQuantity":"5","productVolume":"3,75","eduktName":"Biofuels","eduktQuantity":"40"},
{"typeName":"Livestock","productQuantity":"5","productVolume":"3,75","eduktName":"Proteins","eduktQuantity":"40"},
{"typeName":"Mechanical Parts","productQuantity":"5","productVolume":"3,75","eduktName":"Precious Metals","eduktQuantity":"40"},
{"typeName":"Mechanical Parts","productQuantity":"5","productVolume":"3,75","eduktName":"Reactive Metals","eduktQuantity":"40"},
{"typeName":"Microfiber Shielding","productQuantity":"5","productVolume":"3,75","eduktName":"Industrial Fibers","eduktQuantity":"40"},
{"typeName":"Microfiber Shielding","productQuantity":"5","productVolume":"3,75","eduktName":"Silicon","eduktQuantity":"40"},
{"typeName":"Miniature Electronics","productQuantity":"5","productVolume":"3,75","eduktName":"Chiral Structures","eduktQuantity":"40"},
{"typeName":"Miniature Electronics","productQuantity":"5","productVolume":"3,75","eduktName":"Silicon","eduktQuantity":"40"},
{"typeName":"Nanites","productQuantity":"5","productVolume":"3,75","eduktName":"Bacteria","eduktQuantity":"40"},
{"typeName":"Nanites","productQuantity":"5","productVolume":"3,75","eduktName":"Reactive Metals","eduktQuantity":"40"},
{"typeName":"Nano-Factory","productQuantity":"1","productVolume":"50","eduktName":"Reactive Metals","eduktQuantity":"40"},
{"typeName":"Nano-Factory","productQuantity":"1","productVolume":"50","eduktName":"Ukomi Superconductors","eduktQuantity":"6"},
{"typeName":"Nano-Factory","productQuantity":"1","productVolume":"50","eduktName":"Industrial Explosives","eduktQuantity":"6"},
{"typeName":"Neocoms","productQuantity":"3","productVolume":"9","eduktName":"Biocells","eduktQuantity":"10"},
{"typeName":"Neocoms","productQuantity":"3","productVolume":"9","eduktName":"Silicate Glass","eduktQuantity":"10"},
{"typeName":"Nuclear Reactors","productQuantity":"3","productVolume":"9","eduktName":"Microfiber Shielding","eduktQuantity":"10"},
{"typeName":"Nuclear Reactors","productQuantity":"3","productVolume":"9","eduktName":"Enriched Uranium","eduktQuantity":"10"},
{"typeName":"Organic Mortar Applicators","productQuantity":"1","productVolume":"50","eduktName":"Robotics","eduktQuantity":"6"},
{"typeName":"Organic Mortar Applicators","productQuantity":"1","productVolume":"50","eduktName":"Bacteria","eduktQuantity":"40"},
{"typeName":"Organic Mortar Applicators","productQuantity":"1","productVolume":"50","eduktName":"Condensates","eduktQuantity":"6"},
{"typeName":"Oxides","productQuantity":"5","productVolume":"3,75","eduktName":"Oxygen","eduktQuantity":"40"},
{"typeName":"Oxides","productQuantity":"5","productVolume":"3,75","eduktName":"Oxidizing Compound","eduktQuantity":"40"},
{"typeName":"Oxidizing Compound","productQuantity":"20","productVolume":"3,8","eduktName":"Reactive Gas","eduktQuantity":"3000"},
{"typeName":"Oxygen","productQuantity":"20","productVolume":"3,8","eduktName":"Noble Gas","eduktQuantity":"3000"},
{"typeName":"Planetary Vehicles","productQuantity":"3","productVolume":"9","eduktName":"Miniature Electronics","eduktQuantity":"10"},
{"typeName":"Planetary Vehicles","productQuantity":"3","productVolume":"9","eduktName":"Mechanical Parts","eduktQuantity":"10"},
{"typeName":"Planetary Vehicles","productQuantity":"3","productVolume":"9","eduktName":"Supertensile Plastics","eduktQuantity":"10"},
{"typeName":"Plasmoids","productQuantity":"20","productVolume":"3,8","eduktName":"Suspended Plasma","eduktQuantity":"3000"},
{"typeName":"Polyaramids","productQuantity":"5","productVolume":"3,75","eduktName":"Industrial Fibers","eduktQuantity":"40"},
{"typeName":"Polyaramids","productQuantity":"5","productVolume":"3,75","eduktName":"Oxidizing Compound","eduktQuantity":"40"},
{"typeName":"Polytextiles","productQuantity":"5","productVolume":"3,75","eduktName":"Industrial Fibers","eduktQuantity":"40"},
{"typeName":"Polytextiles","productQuantity":"5","productVolume":"3,75","eduktName":"Biofuels","eduktQuantity":"40"},
{"typeName":"Precious Metals","productQuantity":"20","productVolume":"3,8","eduktName":"Noble Metals","eduktQuantity":"3000"},
{"typeName":"Proteins","productQuantity":"20","productVolume":"3,8","eduktName":"Complex Organisms","eduktQuantity":"3000"},
{"typeName":"Reactive Metals","productQuantity":"20","productVolume":"3,8","eduktName":"Base Metals","eduktQuantity":"3000"},
{"typeName":"Recursive Computing Module","productQuantity":"1","productVolume":"50","eduktName":"Transcranial Microcontrollers","eduktQuantity":"6"},
{"typeName":"Recursive Computing Module","productQuantity":"1","productVolume":"50","eduktName":"Guidance Systems","eduktQuantity":"6"},
{"typeName":"Recursive Computing Module","productQuantity":"1","productVolume":"50","eduktName":"Synthetic Synapses","eduktQuantity":"6"},
{"typeName":"Robotics","productQuantity":"3","productVolume":"9","eduktName":"Consumer Electronics","eduktQuantity":"10"},
{"typeName":"Robotics","productQuantity":"3","productVolume":"9","eduktName":"Mechanical Parts","eduktQuantity":"10"},
{"typeName":"Rocket Fuel","productQuantity":"5","productVolume":"3,75","eduktName":"Plasmoids","eduktQuantity":"40"},
{"typeName":"Rocket Fuel","productQuantity":"5","productVolume":"3,75","eduktName":"Electrolytes","eduktQuantity":"40"},
{"typeName":"Self-Harmonizing Power Core","productQuantity":"1","productVolume":"50","eduktName":"Camera Drones","eduktQuantity":"6"},
{"typeName":"Self-Harmonizing Power Core","productQuantity":"1","productVolume":"50","eduktName":"Hermetic Membranes","eduktQuantity":"6"},
{"typeName":"Self-Harmonizing Power Core","productQuantity":"1","productVolume":"50","eduktName":"Nuclear Reactors","eduktQuantity":"6"},
{"typeName":"Silicate Glass","productQuantity":"5","productVolume":"3,75","eduktName":"Silicon","eduktQuantity":"40"},
{"typeName":"Silicate Glass","productQuantity":"5","productVolume":"3,75","eduktName":"Oxidizing Compound","eduktQuantity":"40"},
{"typeName":"Silicon","productQuantity":"20","productVolume":"3,8","eduktName":"Felsic Magma","eduktQuantity":"3000"},
{"typeName":"Smartfab Units","productQuantity":"3","productVolume":"9","eduktName":"Miniature Electronics","eduktQuantity":"10"},
{"typeName":"Smartfab Units","productQuantity":"3","productVolume":"9","eduktName":"Construction Blocks","eduktQuantity":"10"},
{"typeName":"Sterile Conduits","productQuantity":"1","productVolume":"50","eduktName":"Smartfab Units","eduktQuantity":"6"},
{"typeName":"Sterile Conduits","productQuantity":"1","productVolume":"50","eduktName":"Vaccines","eduktQuantity":"6"},
{"typeName":"Sterile Conduits","productQuantity":"1","productVolume":"50","eduktName":"Water","eduktQuantity":"40"},
{"typeName":"Supercomputers","productQuantity":"3","productVolume":"9","eduktName":"Water-Cooled CPU","eduktQuantity":"10"},
{"typeName":"Supercomputers","productQuantity":"3","productVolume":"9","eduktName":"Consumer Electronics","eduktQuantity":"10"},
{"typeName":"Supercomputers","productQuantity":"3","productVolume":"9","eduktName":"Coolant","eduktQuantity":"10"},
{"typeName":"Superconductors","productQuantity":"5","productVolume":"3,75","eduktName":"Water","eduktQuantity":"40"},
{"typeName":"Superconductors","productQuantity":"5","productVolume":"3,75","eduktName":"Plasmoids","eduktQuantity":"40"},
{"typeName":"Supertensile Plastics","productQuantity":"5","productVolume":"3,75","eduktName":"Biomass","eduktQuantity":"40"},
{"typeName":"Supertensile Plastics","productQuantity":"5","productVolume":"3,75","eduktName":"Oxygen","eduktQuantity":"40"},
{"typeName":"Synthetic Oil","productQuantity":"5","productVolume":"3,75","eduktName":"Electrolytes","eduktQuantity":"40"},
{"typeName":"Synthetic Oil","productQuantity":"5","productVolume":"3,75","eduktName":"Oxygen","eduktQuantity":"40"},
{"typeName":"Synthetic Synapses","productQuantity":"3","productVolume":"9","eduktName":"Supertensile Plastics","eduktQuantity":"10"},
{"typeName":"Synthetic Synapses","productQuantity":"3","productVolume":"9","eduktName":"Test Cultures","eduktQuantity":"10"},
{"typeName":"Test Cultures","productQuantity":"5","productVolume":"3,75","eduktName":"Bacteria","eduktQuantity":"40"},
{"typeName":"Test Cultures","productQuantity":"5","productVolume":"3,75","eduktName":"Water","eduktQuantity":"40"},
{"typeName":"Toxic Metals","productQuantity":"20","productVolume":"3,8","eduktName":"Heavy Metals","eduktQuantity":"3000"},
{"typeName":"Transcranial Microcontrollers","productQuantity":"3","productVolume":"9","eduktName":"Nanites","eduktQuantity":"10"},
{"typeName":"Transcranial Microcontrollers","productQuantity":"3","productVolume":"9","eduktName":"Biocells","eduktQuantity":"10"},
{"typeName":"Transmitter","productQuantity":"5","productVolume":"3,75","eduktName":"Chiral Structures","eduktQuantity":"40"},
{"typeName":"Transmitter","productQuantity":"5","productVolume":"3,75","eduktName":"Plasmoids","eduktQuantity":"40"},
{"typeName":"Ukomi Superconductors","productQuantity":"3","productVolume":"9","eduktName":"Synthetic Oil","eduktQuantity":"10"},
{"typeName":"Ukomi Superconductors","productQuantity":"3","productVolume":"9","eduktName":"Superconductors","eduktQuantity":"10"},
{"typeName":"Vaccines","productQuantity":"3","productVolume":"9","eduktName":"Viral Agent","eduktQuantity":"10"},
{"typeName":"Vaccines","productQuantity":"3","productVolume":"9","eduktName":"Livestock","eduktQuantity":"10"},
{"typeName":"Viral Agent","productQuantity":"5","productVolume":"3,75","eduktName":"Biomass","eduktQuantity":"40"},
{"typeName":"Viral Agent","productQuantity":"5","productVolume":"3,75","eduktName":"Bacteria","eduktQuantity":"40"},
{"typeName":"Water","productQuantity":"20","productVolume":"3,8","eduktName":"Aqueous Liquids","eduktQuantity":"3000"},
{"typeName":"Water-Cooled CPU","productQuantity":"5","productVolume":"3,75","eduktName":"Water","eduktQuantity":"40"},
{"typeName":"Water-Cooled CPU","productQuantity":"5","productVolume":"3,75","eduktName":"Reactive Metals","eduktQuantity":"40"},
{"typeName":"Wetware Mainframe","productQuantity":"1","productVolume":"50","eduktName":"Biotech Research Reports","eduktQuantity":"6"},
{"typeName":"Wetware Mainframe","productQuantity":"1","productVolume":"50","eduktName":"Cryoprotectant Solution","eduktQuantity":"6"},
{"typeName":"Wetware Mainframe","productQuantity":"1","productVolume":"50","eduktName":"Supercomputers","eduktQuantity":"6"},

]
